// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4KlsdDIBtV1Sy9aobbCg9l538mpEMmSo',
    appId: '1:748309767077:web:b01849c99eec9c77dbfe4c',
    messagingSenderId: '748309767077',
    projectId: 'combnultrasoftapp',
    authDomain: 'combnultrasoftapp.firebaseapp.com',
    storageBucket: 'combnultrasoftapp.firebasestorage.app',
    measurementId: 'G-ZPV59RPMPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DSTCBzat3QRK5AaWZxs5o6IzMtQwbmg',
    appId: '1:748309767077:android:1b96e63bc2fec1e2dbfe4c',
    messagingSenderId: '748309767077',
    projectId: 'combnultrasoftapp',
    storageBucket: 'combnultrasoftapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACRu1v4I_S2Oqbb9crzxlRyDm9eXH6d7o',
    appId: '1:748309767077:ios:482060b9b99fe6d2dbfe4c',
    messagingSenderId: '748309767077',
    projectId: 'combnultrasoftapp',
    storageBucket: 'combnultrasoftapp.firebasestorage.app',
    iosBundleId: 'com.bnultrasoft.app.bnultrasoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACRu1v4I_S2Oqbb9crzxlRyDm9eXH6d7o',
    appId: '1:748309767077:ios:482060b9b99fe6d2dbfe4c',
    messagingSenderId: '748309767077',
    projectId: 'combnultrasoftapp',
    storageBucket: 'combnultrasoftapp.firebasestorage.app',
    iosBundleId: 'com.bnultrasoft.app.bnultrasoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4KlsdDIBtV1Sy9aobbCg9l538mpEMmSo',
    appId: '1:748309767077:web:b245e286487969afdbfe4c',
    messagingSenderId: '748309767077',
    projectId: 'combnultrasoftapp',
    authDomain: 'combnultrasoftapp.firebaseapp.com',
    storageBucket: 'combnultrasoftapp.firebasestorage.app',
    measurementId: 'G-90B5XTMGRC',
  );

}